

build:
	clang -O3 -Wno-implicit-int -Wno-deprecated-non-prototype -I/usr/local/sgb/include/ -o sat0 sat0.c -lgb
	clang -O3 -Wno-implicit-int -Wno-deprecated-non-prototype -I/usr/local/sgb/include/ -o sat0w sat0w.c -lgb
	clang -O3 -Wno-implicit-int -Wno-deprecated-non-prototype -I/usr/local/sgb/include/ -o sat8 sat8.c -lgb
	clang -O3 -Wno-implicit-int -Wno-deprecated-non-prototype -Wno-format -I/usr/local/sgb/include/ -o sat9 sat9.c -lgb
	clang -O3 -Wno-implicit-int -Wno-deprecated-non-prototype -I/usr/local/sgb/include/ -o sat10 sat10.c -lgb
	clang -O3 -Wno-implicit-int -Wno-deprecated-non-prototype -I/usr/local/sgb/include/ -o sat11 sat11.c -lgb
	clang -O3 -Wno-implicit-int -Wno-deprecated-non-prototype -I/usr/local/sgb/include/ -o sat11k sat11k.c -lgb
	clang -O3 -Wno-implicit-int -Wno-deprecated-non-prototype -I/usr/local/sgb/include/ -o sat12 sat12.c -lgb
	clang -O3 -Wno-implicit-int -Wno-deprecated-non-prototype -I/usr/local/sgb/include/ -o sat12-erp sat12-erp.c -lgb
	clang -O3 -Wno-implicit-int -Wno-deprecated-non-prototype -I/usr/local/sgb/include/ -o sat13 sat13.c -lgb
	clang -O3 -Wno-implicit-int -Wno-deprecated-non-prototype -I/usr/local/sgb/include/ -o sat-nfa sat-nfa.c -lgb

install:
	cp sat0 /usr/local/bin/
	cp sat0w /usr/local/bin/
	cp sat8 /usr/local/bin/
	cp sat9 /usr/local/bin/
	cp sat10 /usr/local/bin/
	cp sat11 /usr/local/bin/
	cp sat11k /usr/local/bin/
	cp sat12 /usr/local/bin/
	cp sat12-erp /usr/local/bin/
	cp sat13 /usr/local/bin/
	cp sat-nfa /usr/local/bin/